name: Publish GitHub NPM Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  npm-publish:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - run: git config user.email "abdelaliiheb@gmail.com"
      - run: git config user.name "@3bouda"
      - run: git push
      - run: git push --follow-tags

      - name: publish to github
        run: |
          npm config set registry https://npm.pkg.github.com
          npm set //npm.pkg.github.com/:_authToken ${{ env.NODE_AUTH_TOKEN }}
          npm run publish:github
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
