name: Build and Publish Library

on:
  push:
    branches: main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install

      - name: Build the library
        run: ng build

      - name: Archive the build output
        uses: actions/upload-artifact@v3
        with:
          name: library-dist
          path: dist/april-pdf

      - name: Login to npm (if publishing publicly)
        run: |
          if [ ${{ secrets.NPM_TOKEN }} ]; then
            echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
            echo "Successfully logged in to npm registry"
          else
            echo "Skipping npm login as NPM_TOKEN is not provided"
          fi

      - name: Publish the library (if publishing publicly)
        uses: actions/upload-artifact@v3
        with:
          name: library-npm
          path: ~/.npmrc

      - name: Deploy to npm (if publishing publicly)
        run: |
          if [ ${{ secrets.NPM_TOKEN }} ]; then
            cd dist  # Change directory to the build output
            npm publish --access public  # Publish with public access
            echo "Successfully published library to npm"
          else
            echo "Skipping npm publish as NPM_TOKEN is not provided"
          fi